language: go
sudo: false

go:
  - 1.11.x
  - 1.12.x

install:
  - make download

script:
  - make fmt-check
  - make lint
  - make build
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
