on: push
jobs:
  test:
    strategy:
      matrix:
        go: [ '1.10.x', '1.11.x', '1.12.x' ]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
        with:
            path: ./src/github.com/${{ github.repository }}
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: deps
        run:  |
          export PATH=$PATH:$(go env GOPATH)/bin # https://github.com/actions/setup-go/issues/14
          export GOPATH=${{ runner.workspace }}
          make deps
      - name: static program analysis
        run: make fmt-check lint vet
      - name: build
        run: make build
      - name: test
        run: make test
