on: push
jobs:
  lint:
    strategy:
      matrix:
        go: [ '1.10.x', '1.11.x', '1.12.x' ]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: deps
        run: make deps
      - name: static program analysis
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # https://github.com/actions/setup-go/issues/14
          make fmt-check lint vet
      - name: build
        run: make build
      - name: test
        run: make test

  codecov:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Upload Coverage report to CodeCov
        run: bash <(curl -s https://codecov.io/bash)