on: push
jobs:
  test:
    strategy:
      matrix:
        go: [ '1.10.x', '1.11.x', '1.12.x' ]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: deps
        run:  make deps
        env:
          GOPATH: ${{ runner.workspace }}
      - name: static program analysis
        run: |
          export PATH=$PATH:$(go env GOROOT)/bin # https://github.com/actions/setup-go/issues/14
          make fmt-check lint vet
        env:
          GOPATH: ${{ runner.workspace }}
      - name: build
        run: make build
        env:
          GOPATH: ${{ runner.workspace }}
      - name: test
        run: make test
        env:
          GOPATH: ${{ runner.workspace }}
